# Generated by Django 4.2.5 on 2023-09-25 13:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Medico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_medico', models.CharField(max_length=100)),
                ('apellido_medico', models.CharField(max_length=100)),
                ('dni_medico', models.CharField(max_length=100)),
                ('fecha_nac_medico', models.DateField()),
                ('domicilio_medico', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Zona',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_zona', models.CharField(max_length=50)),
                ('cant_pacientes', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Reporte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_reporte', models.CharField(max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('zona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administracion.zona')),
            ],
        ),
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_paciente', models.CharField(max_length=100)),
                ('apellido_paciente', models.CharField(max_length=100)),
                ('dni_paciente', models.CharField(max_length=100)),
                ('fecha_nac_paciente', models.DateField()),
                ('domicilio_paciente', models.CharField(default='', max_length=100)),
                ('genero_paciente', models.CharField(default='', max_length=1)),
                ('telefono_paciente', models.IntegerField(default='')),
                ('email_paciente', models.CharField(default='', max_length=100)),
                ('grupo_sanguineo', models.CharField(default='', max_length=5)),
                ('factor_rh', models.BooleanField(default=False)),
                ('peso_paciente_kg', models.IntegerField(default=0)),
                ('altura_paciente', models.IntegerField(default=0)),
                ('alergias', models.TextField(default='')),
                ('consulta', models.TextField(default='')),
                ('medico_asignado', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='administracion.medico')),
                ('zona', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='administracion.zona')),
            ],
        ),
        migrations.AddField(
            model_name='medico',
            name='zona',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='administracion.zona'),
        ),
    ]
