# Generated by Django 4.2.1 on 2023-09-25 20:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Medico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_medico', models.CharField(max_length=100)),
                ('apellido_medico', models.CharField(max_length=100)),
                ('dni_medico', models.CharField(max_length=100)),
                ('fecha_nac_medico', models.DateField()),
                ('domicilio_medico', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Zona',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_zona', models.CharField(max_length=50)),
                ('cant_pacientes', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Reporte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(default='', max_length=100)),
                ('consulta', models.TextField(default='')),
                ('origen_llamado', models.CharField(default='', max_length=20)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('zona', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='administracion.zona')),
            ],
        ),
        migrations.CreateModel(
            name='Perfil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isCalling', models.BooleanField(default=False)),
                ('isCallingNormal', models.BooleanField(default=False)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_paciente', models.CharField(max_length=100)),
                ('apellido_paciente', models.CharField(max_length=100)),
                ('dni_paciente', models.CharField(max_length=100)),
                ('fecha_nac_paciente', models.DateField()),
                ('medico_asignado', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='administracion.medico')),
                ('perfil', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='administracion.perfil')),
                ('zona', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='administracion.zona')),
            ],
        ),
        migrations.AddField(
            model_name='medico',
            name='zona',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='administracion.zona'),
        ),
        migrations.CreateModel(
            name='Llamado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origen', models.CharField(max_length=20)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('perfil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administracion.perfil')),
                ('zona', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='administracion.zona')),
            ],
        ),
    ]
