# Generated by Django 4.2.1 on 2023-09-25 20:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='llamado',
            name='perfil',
        ),
        migrations.RemoveField(
            model_name='reporte',
            name='origen_llamado',
        ),
        migrations.AddField(
            model_name='llamado',
            name='paciente',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='administracion.paciente'),
        ),
        migrations.AddField(
            model_name='reporte',
            name='llamado',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='administracion.llamado'),
        ),
    ]
