# Generated by Django 4.2.5 on 2023-09-26 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0002_remove_llamado_perfil_remove_reporte_origen_llamado_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='paciente',
            name='alergias',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='paciente',
            name='altura_paciente',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='paciente',
            name='domicilio_paciente',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='paciente',
            name='email_paciente',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='paciente',
            name='genero_paciente',
            field=models.CharField(default='', max_length=1),
        ),
        migrations.AddField(
            model_name='paciente',
            name='grupo_sanguineo',
            field=models.CharField(default='', max_length=5),
        ),
        migrations.AddField(
            model_name='paciente',
            name='peso_paciente_kg',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='paciente',
            name='telefono_paciente',
            field=models.CharField(default='', max_length=10, null=True),
        ),
    ]
