# Generated by Django 4.2.1 on 2023-09-21 23:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0002_paciente_zona'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paciente',
            name='medico_asignado',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='administracion.medico'),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='ubicacion_paciente',
            field=models.CharField(default=None, max_length=100),
        ),
    ]
