# Generated by Django 4.2.1 on 2023-09-28 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0003_paciente_alergias_paciente_altura_paciente_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='zona',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='zonas_fotos/'),
        ),
    ]
