# Generated by Django 4.2.5 on 2023-09-25 14:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0003_perfil'),
    ]

    operations = [
        migrations.AddField(
            model_name='paciente',
            name='perfil',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='administracion.perfil'),
        ),
    ]
