# Generated by Django 4.2.1 on 2023-09-21 23:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0004_remove_paciente_medico_asignado'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paciente',
            name='ubicacion_paciente',
        ),
    ]
