# Generated by Django 4.2.5 on 2023-09-25 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0004_paciente_perfil'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reporte',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='reporte',
            name='tipo_reporte',
        ),
        migrations.RemoveField(
            model_name='reporte',
            name='zona',
        ),
        migrations.AddField(
            model_name='perfil',
            name='isCallingNormal',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='reporte',
            name='consulta',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='reporte',
            name='tipo',
            field=models.BooleanField(default=False),
        ),
    ]
